# Generated by Django 5.1.7 on 2025-04-02 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='00000', max_length=10, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('phone_no', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(default='R000', max_length=10, unique=True)),
                ('branch', models.CharField(default='General', max_length=50)),
                ('is_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(default='SUB000', max_length=10, unique=True)),
                ('subject_name', models.CharField(default='Unknown Subject', max_length=100)),
                ('department', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='Unknown Faculty', max_length=100)),
                ('branch', models.CharField(default='General', max_length=50)),
                ('employee_id', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty', to_field='employee_id')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
            ],
            options={
                'unique_together': {('employee_id', 'subject', 'branch')},
            },
        ),
    ]
